# Generated by Django 2.1.5 on 2019-02-18 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DuolingoUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('last_update', models.DateField(blank=True)),
                ('last_inquiry', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HanDictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traditional', models.CharField(max_length=20)),
                ('simplified', models.CharField(max_length=20)),
                ('pinyin', models.CharField(max_length=255)),
                ('simplified_radical', models.CharField(max_length=20)),
                ('hsk_level', models.IntegerField(blank=True, null=True)),
                ('frequency_rank', models.IntegerField(blank=True, null=True)),
                ('phrase_url', models.URLField()),
                ('radical_url', models.URLField()),
                ('definition', models.TextField()),
            ],
        ),
    ]
