# Generated by Django 2.1.5 on 2019-02-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190218_0938'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phraseid', models.IntegerField(blank=True, null=True)),
                ('question', models.TextField(blank=True, null=True)),
                ('answer', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
