# Generated by Django 2.1.5 on 2019-02-19 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_testanswers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestAnswers',
        ),
    ]
